### ISSUE TITLE
Unable to export configuration as code

### ISSUE THREAD

**Issue by multani** [jenkinsci/nomad-plugin#54]
I tried a basic Jenkins installation with the Nomad Plugin and the [Configuration as code plugin](https://plugins.jenkins.io/configuration-as-code).

I setup a new "Nomad cloud" with a super basic template as in the screenshot (the other fields are empty):

![image](https://user-images.githubusercontent.com/65311/62323599-f4234100-b4a7-11e9-921a-8b11570ddc08.png)

Then, exporting this configuration using JENKINS/configuration-as-code/viewExport produces an infinite loop followed by a `java.lang.StackOverflowError` error.

The exported YAML configuration by the "Configuration as code" plugin, when it manages to output something, produces something like:

```yaml
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - nomad:
      jenkinsUrl: "http://localhost:8080/"
      name: "nomad"
      nomadUrl: "http://127.0.0.1:4646"
      prune: false
      slaveUrl: "http://localhost:8080/jnlpJars/slave.jar"
      templates:
      - cloud:
          jenkinsUrl: "http://localhost:8080/"
          name: "nomad"
          nomadUrl: "http://127.0.0.1:4646"
          prune: false
          slaveUrl: "http://localhost:8080/jnlpJars/slave.jar"
          templates:
          - cloud:
              jenkinsUrl: "http://localhost:8080/"
              name: "nomad"
              nomadUrl: "http://127.0.0.1:4646"
              prune: false
              slaveUrl: "http://localhost:8080/jnlpJars/slave.jar"
              templates:
              - cloud:
                  jenkinsUrl: "http://localhost:8080/"
                  name: "nomad"
                  nomadUrl: "http://127.0.0.1:4646"
                  prune: false
                  slaveUrl: "http://localhost:8080/jnlpJars/slave.jar"
                  templates:
                  - cloud:
                      jenkinsUrl: "http://localhost:8080/"
                      name: "nomad"
                      nomadUrl: "http://127.0.0.1:4646"
                      prune: false
                      slaveUrl: "http://localhost:8080/jnlpJars/slave.jar"
                      templates:
                      - cloud:
                          jenkinsUrl: "http://localhost:8080/"
                          name: "nomad"
                          nomadUrl: "http://127.0.0.1:4646"
                          prune: false
                          slaveUrl: "http://localhost:8080/jnlpJars/slave.jar"
                          templates:
                          - cloud:
                              ... # repeats ad vitam æternam
```

There's the related issue [JENKINS-58491](https://issues.jenkins-ci.org/browse/JENKINS-58491) on Jira but it pings Ivo Verberk and the issue has been closed since then, although I think the original recursion problem describe in the issue is actually still present in the plugin.

It would be cool if we could use both plugins together and backup/reconfigure the Nomad Plugin configuration using the Configuration as Code plugin! :+1:
