### ISSUE TITLE
Casc configuration requires manual save after restart

### ISSUE THREAD

**Issue by SimonVleugels** [jenkinsci/nomad-plugin#68]
Hi,
I have a nomad cloud configuration setup with casc. The configuration works fine and is correctly filled in, but requires to manually save the configuration again every time jenkins restarts. If you don't do this Jenkins will keep trying to start new workers which keep failing with error: `This agent is offline because Jenkins failed to launch the agent process on it.`. There are no extra logs and there is no job created on the nomad cluster.

nomad cloud casc:
```
jenkins:
  clouds:
    - nomad:
        jenkinsUrl: "${JENKINS_URL}"
        name: "***"
        nomadACLCredentialsId: "nomad-token"
        nomadUrl: "http://***:4646"
        prune: true
        templates:
        - cpu: 100
          datacenters: "***"
          disk: 300
          forcePull: false
          hostVolumes: "/var/run/docker.sock:/var/run/docker.sock,/tmp:/home/jenkins"
          idleTerminationInMinutes: 10
          image: "***"
          labels: "***"
          memory: 300
          network: "bridge"
          numExecutors: 1
          password: "${token}"
          prefix: "jenkins-worker"
          priority: 50
          privileged: true
          region: "global"
          remoteFs: "/home/jenkins"
          reusable: true
          useRawExec: false
          username: "${username}"
        workerTimeout: 10
        workerUrl: "${JENKINS_URL}/jnlpJars/slave.jar"

```
